drivers: firmware: efi: Fix build error due to mmap_sem to mmap_lock rename
efi_mm was still initializing the old '.mmap_sem' field of
struct mm_struct, but mm_types.h has since been renamed to
'mmap_lock' (mmap locking API rename), breaking the build:

drivers/firmware/efi/efi.c:81:42: error: no member named 'mmap_sem' in 'struct mm_struct'
   81 |         .mmap_sem               = __RWSEM_INITIALIZER(efi_mm.mmap_sem),

Signed-off-by: sayann70 <sayansarkarda2@gmail.com>